# Generated by Django 2.2 on 2019-04-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('barrel_caliber', models.IntegerField()),
                ('barrel_rate_of_fire', models.IntegerField()),
                ('turret', models.BooleanField()),
                ('turret_caliber', models.IntegerField()),
                ('front_armor', models.BooleanField()),
                ('side_armor', models.BooleanField()),
            ],
        ),
    ]
